// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs5WdZMb478rkOC5XcztJ8m3dN5UTd0MY',
    appId: '1:665466753768:web:7e354fcdc6f84a52a6ef5d',
    messagingSenderId: '665466753768',
    projectId: 'movies-7d910',
    authDomain: 'movies-7d910.firebaseapp.com',
    storageBucket: 'movies-7d910.firebasestorage.app',
    measurementId: 'G-485XEGGBND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7Nf3NvZ-B4ItJSYk0u7_R8Jfclpb4SQA',
    appId: '1:665466753768:android:76747b4199a2a1f4a6ef5d',
    messagingSenderId: '665466753768',
    projectId: 'movies-7d910',
    storageBucket: 'movies-7d910.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5clb03_yWTRPXlYSv_kSwtyLJPmugLFk',
    appId: '1:665466753768:ios:ef3004662e30c6a2a6ef5d',
    messagingSenderId: '665466753768',
    projectId: 'movies-7d910',
    storageBucket: 'movies-7d910.firebasestorage.app',
    iosBundleId: 'com.example.moviesApp',
  );
}
